name: Deploy Blog

on:
  push:
    branches: 
      - master
env:
  TZ: Asia/Shanghai

jobs:
  build: # 一项叫做build的任务

    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    
    steps:
    - name: Checkout # 1. 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v2 # 脚本来自 https://github.com/actions/checkout
      with: 
        submodule: 'true' 
      
    - name: Setup Node.js # 2. 配置Node环境
      uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: '12'
    - name: SetupHexoEnvironment
      run: |
        npm install -g hexo-cli
        npm ci
    
     #- name: Setup Hexo env #3. 设置 Hexo 环境变量 
      #env:
      #  ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
      #run: |
        # set up private key for deploy
        # mkdir -p ~/.ssh/
        # echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        # chmod 600 ~/.ssh/id_rsa
        # ssh-keyscan github.com >> ~/.ssh/known_hosts
        # set git infomation
        # git config --global user.name 'stardustman' # 换成你自己的邮箱和名字
        # git config --global user.email 'aoyunyoung@gmail.com'
        # install dependencies
        # npm install -g hexo-cli
        # npm ci
 
        
  
    - name: Deploy
      run: |
        # publish
        hexo generate && hexo deploy # 执行部署程序
